### ISSUE TITLE
Embedded fonts not rendered

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10247]
_**[fcam...@gmail.com](http://code.google.com/u/106812579790779250704/) commented:**_

> <b>Which version of PhantomJS are you using? Tip: run 'phantomjs --version'.</b>
> 
> 1.3.0
> 
> <b>What steps will reproduce the problem?</b>
> 1. phantomjs --load-plugins=yes rasterize.js http://www.nodecloud.org nodecloud.png
> 2. phantomjs --load-plugins=yes rasterize.js http://vowsjs.org vowsjs.png
> 
> <b>What is the expected output? What do you see instead?</b>
> 
> Embedded fonts (@font-face CSS property) should be rendered, but system fonts are rendered instead.
> 
> <b>Which operating system are you using?</b>
> 
> Linux
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> 
> Compiled it from source.
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #247](http://code.google.com/p/phantomjs/issues/detail?id=247).
:star2: &nbsp; **21** people had starred this issue at the time of migration.

**Comment by zackw** [comment]
Unfortunately, this seems still to be a problem with PhantomJS 2.0, per the test case at http://dev.increment.org/fonts/ (thanks for keeping that around!)  Note that both of the desktop browsers I screenshotted below were running on OSX, whereas PhantomJS was running on Linux.  This is almost certainly either a Webkit core issue, or a platform-font-library issue.

### PhantomJS

![Rendering of test case at http://dev.increment.org/fonts/ using PhantomJS 2.0](https://cloud.githubusercontent.com/assets/325899/7236541/9ca79860-e763-11e4-8c2b-ac1aea08ab6a.png)

### Safari

![Rendering of test case at http://dev.increment.org/fonts/ using Safari 6 on OSX 10.10](https://cloud.githubusercontent.com/assets/325899/7236634/f8b1458e-e763-11e4-856d-71e4e235af99.png)

### Firefox

![Rendering of test case at http://dev.increment.org/fonts/ using Firefox on OSX 10.10](https://cloud.githubusercontent.com/assets/325899/7236567/bc43d3e6-e763-11e4-8de5-464fda9dcb7b.png)

**Comment by theaspect** [comment]
Looks like workaround is to put fonts locally like http://chapter31.com/2012/09/24/installing-new-fonts-on-ubuntu-server/

**Comment by Vitallium** [comment]
Fixed in 2.5.

**Comment by holic** [comment]
@Vitallium That's great news! Thanks for all your work!

Where was this fixed? Is it possible to run the latest code with this fix prior to release? And when is 2.5 slated for release?

**Comment by Vitallium** [comment]
@holic yes, beta binaries available on the same page: https://bitbucket.org/ariya/phantomjs/downloads

**Comment by VzqzAc** [comment]
I'm still having the issue with 2.5 but maybe I'm doing something wrong, could anyone relate?

**Comment by olegsfinest** [comment]
I am also still having the same problem. Using fonts defined in `@font-face` that i have locally on the (linux-)server that should be rendered into the pdf are not beeing used.
