### ISSUE TITLE
setTimeout ignores timeout when called from page.includeJs() callback

### ISSUE THREAD

**Issue by ariya** [ariya/phantomjs#10832]
_**[chri...@parastudios.de](http://code.google.com/u/113428024598645356313/) commented:**_

> Which version of PhantomJS are you using? Tip: run 'phantomjs --version'. =&gt; 1.7.0 win7 x64
> 
> <b>What steps will reproduce the problem?</b>
> Run the attached JS file with phantomjs. 
> It will try and load google.com, include jQuery - both work fine and then tries do perform a setTimeout of 5 seconds. The function passed to setTimeout is called immediately.
> 
> <b>What is the expected output? What do you see instead?</b>
> After the console log &quot;BeforeTimeout&quot; I expect 5 seconds to pass before &quot;AfterTimeout&quot; is written to the console. Instead, &quot;AfterTimeout&quot; is written instantly to the console.
> 
> <b>Which operating system are you using?</b>
> Win7 x64
> 
> <b>Did you use binary PhantomJS or did you compile it from source?</b>
> Binary
> 
> <b>Please provide any additional information below.</b>

**Disclaimer:**
This issue was migrated on 2013-03-15 from the project's former issue tracker on Google Code, [Issue #832](http://code.google.com/p/phantomjs/issues/detail?id=832).
:star2: &nbsp; **6** people had starred this issue at the time of migration.

**Comment by simonklb** [comment]
I have this issue as well. No delay on the timeout callback.

**Comment by apendua** [comment]
@simonklb Which version of phantomjs are you working with? I thought it was already resolved in one of the recent releases.

**Comment by simonklb** [comment]
@apendua I got the build in the Ubuntu repo. Version 1.9.0. Which version is this solved in?

**Comment by apendua** [comment]
In that case you're using pretty outdated version. I guess you should try `1.9.8`.

**Comment by simonklb** [comment]
Looks like it's working, thanks! This should perhaps be marked as resolved then?

**Comment by jeffreytu** [comment]
Just a note for users. 1.9.8 still had the setTimeout bug when I tried it. I updated to 2.0 and setTimeout works properly.

**Comment by richthofen911** [comment]
The setTimeout still doesn't work on my Fedora 21, phantomjs version 2.0

**Comment by ashafer01** [comment]
Still happening for me - PhantomJS 2.0 built from source on RHEL 6.3.

**Comment by PavelPolyakov** [comment]
@ashafer01 
use http://casperjs.org/ , which laverages the phantomjs. No issues with setTimeout

**Comment by MartelBenjamin** [comment]
Still no working for me with Win 7 and phantom 2.0

**Comment by coderfantasy** [comment]
https://newspaint.wordpress.com/2013/08/15/phantomjs-window-settimeout-appears-to-be-ignored/

solve my issue

**Comment by muchhalsagar88** [comment]
Still facing the issue on Mac!!

**Comment by Pistos** [comment]
Bump.  I have some code under test which uses `setTimeout`, the interval is ignored, the callback executes immediately.  I have the callback recurse on itself (it's a classic "wait for" pattern), but the recursion always dies after 3 iterations.  Versions:

* PhantomJS 2.0.0
* poltergeist 1.9.0 (Ruby gem)
* Capybara 2.7.1 (Ruby gem)

The exact same spec passes 100% of the time when I have Capybara execute in Firefox instead of PhantomJS.

**Comment by Pistos** [comment]
In fairness, I have tried to set up a minimal example, and could do it.  Something is particular to my code (websockets?) which is causing the problem.

**Comment by georgiosd** [comment]
Wow, this bug has been open for 4 years and still no resolution?

**Comment by frazras** [comment]
Solution:
       `setTimeout(function(){
            setTimeout(function(){
                //Your function here
            },700);
        },1);`

**Comment by apendua** [comment]
@frazras I remember using this fix ~3 years ago. It worked for some time and then it broke again with another release of `phantomjs`. Glad to hear it's working again, but I am also surprised that this issue has not been resolved for so long.

**Comment by apendua** [comment]
@frazras Right on time :)

https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by merlinthemagic** [comment]
I have been struggling with this issue as well. Did some quick tests to see if it was related to load.

Which version of PhantomJS are you using? Tip: run 'phantomjs --version
2.1.1 

Which operating system are you using?
CentOS7

Did you use binary PhantomJS or did you compile it from source?
Binary

What steps will reproduce the problem?

Construct a HTML document with a number of Divs.  I did it in PHP (see attachment)
[generateHTML.php.txt](https://github.com/ariya/phantomjs/files/1099962/generateHTML.php.txt)


start a setTimeout loop and have PhantomJS open the html we just generated, vanilla page.open logic:

```
var count = 0;
function counter()
{
  setTimeout(function()
  { 
    count++;
    counter();
  }, 100);
}
function openPage()
{
  counter();
  var sTime = (new Date).getTime() / 1000;
  var url = http://devserver.example.com/test.htm
  page.open(url,  function(status) {
    var duration =  sTime  - (new Date).getTime() / 1000;
    console.log(duration);
    console.log(count);
  });
}

openPage();
```

The count is always 1. I then increase the number of Divs and measure how long it takes PhantomJS to open on localhost + memory consumption. CPU is locked at 100% when opening the page, i get memory from bash. 

Here are the results:

![2017-06-24_201423](https://user-images.githubusercontent.com/8021715/27511356-bd63ef8e-5919-11e7-8f7e-321d7fd9a1e7.png)


As you can see there is not a linear relationship between the size of the document and load time or memory consumption. Also it appears page.open blocks all other processing.

Opening HTML with ~1200 divs causes PhantomJS to consume 10GB+ memory and almost 5 minutes just to open the page on a gigabit network.

This is the root cause of many exceptions when opening pages. I do not know C++ or i would help find the structure that causes memory and execution time to grow exponentially.


1. What might be the reason PhantomJS does not scale linearly with the size of the document?
2.  Is it possible to push certain functions off the main thread?
