### ISSUE TITLE
PhantomJS client died while processing....

### ISSUE THREAD

**Issue by ryan-mars** [ariya/phantomjs#11246]
Running this spec file crashes PhantomJS on OSX 10.8.3 using Rails 4.0.0.beta1 and Ruby 2.0.0p0. Dump file can be found here: https://www.dropbox.com/s/e81n6m1ok6d3rrd/68A3044A-FEAE-4A31-AD14-377D881DC1E9.dmp

``` ruby
require 'spec_helper'
require 'capybara/poltergeist'
include Capybara::DSL
Capybara.javascript_driver = :poltergeist

describe 'some stuff which requires js', :js => true do
  it 'will take a screenshot' do
    visit("http://google.com")
    page.driver.render('/Users/ryan/Desktop/file.png', :full => true)
  end
end
```

**Comment by ajsharp** [comment]
Still seeing this issue on CirceCI, which currently installs phantomJS 1.9.8 on all nodes.

**Comment by SubhashShah-BTC** [comment]
+1 facing this problem on Travis CI with phantomJS 1.9.8. Is there any fix available ?

**Comment by CID-DAVE** [comment]
did anyone manage to find out the reason for this error.

**Comment by waleedarshad-vf** [comment]
+1

**Comment by CID-DAVE** [comment]
My solution was to use 1.10.0 and upgrade to phantomjs  2.1.1 version.

**Comment by pengisgood** [comment]
+1 Still facing this issue on `Jenkins` with phantomjs `1.9.6`
