### ISSUE TITLE
Resource request error: 6 ( "SSL handshake failed" )

### ISSUE THREAD

**Issue by ghost** [ariya/phantomjs#12440]
Some https websites failed to to load. Debug report contains this below message.

```
2014-08-10T10:05:40 [DEBUG] CookieJar - Created but will not store cookies (use option '--cookies-file=<filename>' to enable persisten cookie storage) 
2014-08-10T10:05:40 [DEBUG] Phantom - execute: Configuration 
2014-08-10T10:05:40 [DEBUG]      0 objectName : "" 
2014-08-10T10:05:40 [DEBUG]      1 cookiesFile : "" 
2014-08-10T10:05:40 [DEBUG]      2 diskCacheEnabled : "false" 
2014-08-10T10:05:40 [DEBUG]      3 maxDiskCacheSize : "-1" 
2014-08-10T10:05:40 [DEBUG]      4 ignoreSslErrors : "true" 
2014-08-10T10:05:40 [DEBUG]      5 localToRemoteUrlAccessEnabled : "false" 
2014-08-10T10:05:40 [DEBUG]      6 outputEncoding : "UTF-8" 
2014-08-10T10:05:40 [DEBUG]      7 proxyType : "http" 
2014-08-10T10:05:40 [DEBUG]      8 proxy : ":1080" 
2014-08-10T10:05:40 [DEBUG]      9 proxyAuth : ":" 
2014-08-10T10:05:40 [DEBUG]      10 scriptEncoding : "UTF-8" 
2014-08-10T10:05:40 [DEBUG]      11 webSecurityEnabled : "false" 
2014-08-10T10:05:40 [DEBUG]      12 offlineStoragePath : "" 
2014-08-10T10:05:40 [DEBUG]      13 offlineStorageDefaultQuota : "-1" 
2014-08-10T10:05:40 [DEBUG]      14 printDebugMessages : "true" 
2014-08-10T10:05:40 [DEBUG]      15 javascriptCanOpenWindows : "true" 
2014-08-10T10:05:40 [DEBUG]      16 javascriptCanCloseWindows : "true" 
2014-08-10T10:05:40 [DEBUG]      17 sslProtocol : "any" 
2014-08-10T10:05:40 [DEBUG]      18 sslCertificatesPath : "" 
2014-08-10T10:05:40 [DEBUG]      19 webdriver : ":" 
2014-08-10T10:05:40 [DEBUG]      20 webdriverLogFile : "" 
2014-08-10T10:05:40 [DEBUG]      21 webdriverLogLevel : "INFO" 
2014-08-10T10:05:40 [DEBUG]      22 webdriverSeleniumGridHub : "" 
2014-08-10T10:05:40 [DEBUG] Phantom - execute: Script & Arguments 
2014-08-10T10:05:40 [DEBUG]      script: "capture.js" 
2014-08-10T10:05:40 [DEBUG]      0 arg: "https://0.s3.envato.com/files/93685175/icon80x80.png" 
2014-08-10T10:05:40 [DEBUG] Phantom - execute: Starting normal mode 
2014-08-10T10:05:40 [DEBUG] WebPage - setupFrame "" 
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/fs.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/system.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/_coffee-script.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/package.json" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/coffee-script.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./lexer.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/././rewriter.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/././helpers.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./parser.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./helpers.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./nodes.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/././scope.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./././helpers.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/././lexer.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/../coffee-script/./lib/coffee-script/./././rewriter.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] FileSystem - _open: ":/modules/webpage.js" QMap(("mode", QVariant(QString, "r") ) )  
2014-08-10T10:05:40 [DEBUG] WebPage - updateLoadingProgress: 10 
2014-08-10T10:05:40 [DEBUG] Network - Resource request error: 6 ( "SSL handshake failed" ) URL: "https://0.s3.envato.com/files/93685175/icon80x80.png" 
2014-08-10T10:05:40 [DEBUG] WebPage - updateLoadingProgress: 100 
```

How to fix this error.

**Comment by iliakan** [comment]
QT5 must support SNI is enabled.

But I get "SSL handshake failed" when working with cloudflare-SSL. What a surprise.

@ariya could you please say a word here, it really should work by default.

**Comment by bompi88** [comment]
@iliakan did you get it to work?

**Comment by iliakan** [comment]
@bompi88 can't remember, not sure.

**Comment by eiriksm** [comment]
FWIW. I am using cloudflare ssl for a couple of sites i am requesting regularly. It works for me, but I had to use 2.0. Although this build is now probably a year old, almost. So not sure if there is any difference in master and my build. But I absolutely had to switch to 2.0 at least.

**Comment by iliakan** [comment]
FWIW I had free cloudflare account, paid certificate is better, maybe it's ok.

**Comment by bompi88** [comment]
Ok, thanks guys. I'm compiling phantomjs 2.0.0 on linux now, which takes forever btw. But worth a shot.

**Comment by morozgrafix** [comment]
@bompi88 did PhantomJS 2.x on linux help?

**Comment by Shance** [comment]
Just builded PhantomJS 2.0 from sources under Fedora 22 (there was a bug with QT5.0 i think, this helped: https://codereview.qt-project.org/#/c/107921/3/Source/JavaScriptCore/runtime/JSObject.cpp)
And i still got this error `"SSL handshake failed"` even with `--ssl-protocol=tlsv1`, `--ssl-protocol=any`, `--web-security=false` and `--ignore-ssl-errors=true`.
When i use `--ignore-ssl-errors=true` I get `"Operation canceled"` but it still fails
Any suggestions?

**Comment by gmisura** [comment]
Verify it works with openssl:

openssl s_client host:port
<wait>
GET / HTTP/1.1<enter><enter>

I ran into a problem where Amazon cloud could not connect to a specific
host:443. Moved to google cloud, worked fine.

On Thu, Jun 25, 2015 at 1:26 PM, Николай <notifications@github.com> wrote:

> Just builded PhantomJS 2.0 from sources under Fedora 22 (there was a bug
> with QT5.0 i think, this helped:
> https://codereview.qt-project.org/#/c/107921/3/Source/JavaScriptCore/runtime/JSObject.cpp
> )
> And i still got this error "SSL handshake failed" even with
> --ssl-protocol=tlsv1, --ssl-protocol=any, --web-security=false and
> --ignore-ssl-errors=true.
> When i use --ignore-ssl-errors=true I get "Operation canceled" but it
> still fails
> Any suggestions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ariya/phantomjs/issues/12440#issuecomment-115309460>.
>



-- 
Gabe Misura

**Comment by Shance** [comment]
I'm sorry, but i don't understand what are you trying to say.
when I do `openssl s_client -connect HOST:443 -showcerts` I get `Verify return code: 21 (unable to verify the first certificate)`
I allready download this cert by doing this `openssl s_client -showcerts -connect HOST:443 </dev/null 2>/dev/null|openssl x509 -outform PEM >mycertfile.pem` but I don't know hot to use it with PhantomJS
it(https://github.com/ariya/phantomjs/issues/10524) looks like PhantomJS can't use my certificate.
So what I need to do to get my js script works?

**Comment by gmisura** [comment]
I didn't really investigate my issue very much so I'm not sure I'm going to
be a lot of help, but...

Is it a self signed cert or a "real" cert issued by a CA (Certificate
Authority)?

You probably can use this option

  --ssl-certificates-path=<val>        Sets the location for custom CA
certificates (if none set, uses system default)

To point at the cert you downloaded.

On Thu, Jun 25, 2015 at 1:53 PM, Николай <notifications@github.com> wrote:

> I'm sorry, but i don't understand what are you trying to say.
> when I do openssl s_client -connect HOST:443 -showcerts I get Verify
> return code: 21 (unable to verify the first certificate)
> I allready download this cert by doing this openssl s_client -showcerts
> -connect HOST:443 </dev/null 2>/dev/null|openssl x509 -outform PEM
> >mycertfile.pem but I don't know hot to use it with PhantomJS
> it(#10524 <https://github.com/ariya/phantomjs/issues/10524>) looks like
> PhantomJS can't use my certificate.
> So what I need to do to get my js script works?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ariya/phantomjs/issues/12440#issuecomment-115322359>.
>



-- 
Gabe Misura

**Comment by Shance** [comment]
It's a real signed Certificate, but still Chrome display it with yellow lock.
And it's getting weirder, because some pages of this web site load normally with `--ignore-ssl-errors=true` but other fails with `"Operation canceled"`. The only one difference between page is that pages with alert() on them fails, and without it loads fine. But it's seems too crazy for me, so I don't really know what is wrong with it.

**Comment by gmisura** [comment]
maybe handle the alert with

http://phantomjs.org/api/webpage/handler/on-alert.html

On Thu, Jun 25, 2015 at 4:29 PM, Николай <notifications@github.com> wrote:

> It's a real signed Certificate, but still Chrome display it with yellow
> lock.
> And it's getting weirder, because some pages of this web site load
> normally with --ignore-ssl-errors=true but other fails with "Operation
> canceled". The only one difference between page is that pages with
> alert() on them fails, and without it loads fine. But it's seems too crazy
> for me, so I don't really know what is wrong with it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ariya/phantomjs/issues/12440#issuecomment-115370235>.
>



-- 
Gabe Misura

**Comment by Shance** [comment]
That was my guess too. But with it and without it - result the same

**Comment by bompi88** [comment]
@morozgrafix yes it solved my case. Took a long time though.

**Comment by iambibhas** [comment]
When you the 2.0.0 binary for linux x86_64 be available here https://bitbucket.org/ariya/phantomjs/downloads ? I wanted to build it, but my tiny DigitalOcean doesn't have enough memory and it exited midways. Getting the SSL Handhake error on 1.9.8 and want to try 2.0.0 to see if that fixes it, but can't.

**Comment by ilyaevseev** [comment]
The same problem with PhantomJS 1.9.0 from Ubuntu debs and 1.9.8 from Bitbucket.
Cannot connect to Cloudflare-protected site via HTTPS.
Is it fixed in 2.0?

(it seems that #11239 and #12440 can be merged)

**Comment by ricohumme** [comment]
using --ssl-protocol=tlsv1 fixed it on my end

**Comment by FlorianBador** [comment]
I found an example of website where I ALWAYS reproduce this issue:
**https://www.missionbicycle.com/**
I use all of these: --web-security=false --ssl-protocol=tlsv1 --ignore-ssl-errors=true and it doesn't change anything, still get **"ERR1    6 SSL handshake failed"**
Anyone is getting this example to work?
I don't know what is different about it but this specific URL works fine in all browsers.

**Comment by r1b** [comment]
One shouldn't have to neuter SSL to access HTTPS pages with phantomjs.

**Comment by FlorianBador** [comment]
Amen,

**Comment by richwandell** [comment]
I am also experiencing the same issue. Any fix on the horizon?
