### ISSUE TITLE
Fails to fetch web resource with HTTPS connection on up-to-date Ubuntu-16.04.3

### ISSUE THREAD

**Issue by rodush** [ariya/phantomjs#15223]
1. Which version of PhantomJS are you using? Tip: run `phantomjs --version`.
`2.1.1` (Resolved to 2.1.7, although in packages.json we have phantomjs-prebuilt: 2.1.16)

2. What steps will reproduce the problem?
  A. Upgraded to the latest at the moment version of Ubuntu-16.04
  B. Try to download a web resource from HTTPS, e.g.:
`phantomjs test.js`
where test.js contents is:
```js
var page = require('webpage').create();

page.onError = function (msg, trace) {
    console.log(msg);
    trace.forEach(function(item) {
        console.log('  ', item.file, ':', item.line);
    });
};
page.onResourceRequested = function (request) {
    console.log('Request ' + JSON.stringify(request, undefined, 4));
};
page.onResourceReceived = function(response) {
    console.log('Receive ' + JSON.stringify(response, undefined, 4));
};

page.open('https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js', function(status) {
//page.open('https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js', function(status) {
//page.open('https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js', function(status) {
    console.log("Status: " + status);
    if(status === "success") {
        page.render('example.png');
    }
    phantom.exit();
});
```
  C. Observe output "Status: fail" in console. 
  D. When use HTTP access, the Status reports "success".

3. Which operating system are you using?
`Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-104-generic x86_64)`

4. Did you use binary PhantomJS or did you compile it from source?
Installed with `npm install -g`

5. Please provide any additional information below.
Node `v8.9.0`
NPM `v5.5.1`
Yarn `1.2.1`

The situation started to appear after I made this upgrade:

```
$ sudo apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  libboost-filesystem1.58.0 libboost-program-options1.58.0 libboost-system1.58.0 libboost-thread1.58.0 libgoogle-perftools4 liblockfile-bin liblockfile1 libpcrecpp0v5 libsnappy1v5 libsnmp-base
  libsnmp30 libtcmalloc-minimal4 libunwind8 libv8-3.14.5 libvpx3 libyaml-cpp0.5v5 m4 procmail sendmail-base sendmail-cf sensible-mda snmp
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  golang-1.6 golang-1.6-doc golang-1.6-go golang-1.6-src grub-legacy-ec2 libperl5.22 libpq-dev libpq5 libssl-dev libssl1.0.0 libssl1.1 lshw openjdk-8-jre-headless openssl perl perl-base
  perl-modules-5.22 php7.2-common postgresql-9.5 postgresql-client-9.5 postgresql-client-common postgresql-common postgresql-contrib-9.5 resolvconf snapd tzdata ubuntu-core-launcher ubuntu-minimal
  ubuntu-server
29 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 89.1 MB of archives.
After this operation, 8492 kB of additional disk space will be used.
Do you want to continue? [Y/n]
```

I suspect it has something to do with SSL related Ubuntu packages. 
Unfortunately, can't prove it, so maybe for authors of PhantomJS it's more clear how to debug.

I tried on different machines, and with latest, up-to-date Ubuntu-16.04 this situation reproduces.

Works fine on MacOS X though...

**Comment by rodush** [comment]
Okay, small updated here:
I found this issue https://github.com/ariya/phantomjs/issues/12181 and decided to give it a try.
So, with `--ignore-ssl-errors=true` seem to work fine.... Hope it gives more information.

**Comment by pixiuPL** [comment]
@rodush Thanks for reporting this. Will investigate.
/cc @Vitallium @ariya any thoughts?

**Comment by Vitallium** [comment]
I believe rebuilding binaries with latest OpenSSL version should fix this problem.

**Comment by rodush** [comment]
In my case it is just a VPS, with Ubuntu-16.04 installed. Fully controlled by myself (as much as my knowledge of Unix helps me to control the server :-) )
But also situation reproduced on any Vagrantbox for Ubuntu-16.04

Although with --ingore-ssl-errors resources seem to be downloaded, still Karma crashes with cryptic "Script error" message...
I'm trying to find a way how I can debug from my MacOS host, when test suit is being run inside Vagrant....

**Comment by rodush** [comment]
@Vitallium I decided to check what openssl I have, and see quite weird situation:
> ii  openssl                              1.1.0g-2.1+ubuntu16.04.1+deb.sury.org+1                  amd64        Secure Sockets Layer toolkit - cryptographic utility

...and when I check https://launchpad.net/ubuntu/+source/openssl, it shows quite interesting information: this version of package is not-official / untrusted, so I need to find out how and why it gets installed to the latest Ubuntu-16.04.

<img width="649" alt="screen shot 2017-12-21 at 12 07 46" src="https://user-images.githubusercontent.com/1138060/34253455-e8bc0b74-e647-11e7-9940-8c58f94530e2.png">

**Comment by pixiuPL** [comment]
@rodush VPS or not - its hosted on AWS.... otherwise there would not be `grub-legacy-ec2` package, as AWS does not ship their custom made pkgs outside of their distros.....

What will happen if you make switch from openssl to Lets Encrypt? Would this problem persist or be gone?

**Comment by rodush** [comment]
Thanks for helping to investigate this.
The output which I took, was from a Vagrantbox (Ubuntu-16.04), it is not hosted on AWS.
Another server (our CI), is a VPS which I meant, doesn't have that library, but still the same issue.
I can not get rid of openssl as this library is needed for PHP-7.1 to be installed in Ubuntu-16.04, unfortunately...
I think the bug is not in PhantomJS itself, but at least that is where it crashes... Other people under same conditions as mine (Ubuntu-16.04 + PHP-7.1 + PhantomJS/Karma), might have similar trouble at some point in time. Like I said, the combination worked until I upgraded Ubuntu...
So feel free to close this task, if you guys don't have time to reproduce / investigate.

**Comment by pixiuPL** [comment]
we (at least I) will not close this; openssl is indeed needed by php, but once you install (anbd configure) Lets Encrypt, it will run paralelly to openssl. For me its worth trying. Dont worry, you will break nothing.....

**Comment by rodush** [comment]
Hi, @pixiuPL !
What exactly do you mean by installing and configuring lets encrypt?
I'm not afraid on installing it, it's just I don't clearly understand what to install... Do you mean `certbot` utility?

**Comment by pixiuPL** [comment]
@rodush sorry for the delay.
Just go [here](https://certbot.eff.org), select your web-server, your operating system and simplyu follow the instructions. Just simple as this.

**Comment by rodush** [comment]
@pixiuPL why did you close it?
If you want to reproduce, just grab a fresh clean official [ubuntu/xenial-16.04](https://app.vagrantup.com/ubuntu/boxes/xenial64) on Hashicorp Atlas, install node `8.9.4` inside, instal `phantomjs` with `npm i -g phantomjs` and try to run the test script which I attached in the issue description.
Result is exactly the same, so it is not even connected to the unofficial openssl library which gets installed for PHP-7.x: 

<img width="943" alt="screen shot 2018-01-22 at 17 40 59" src="https://user-images.githubusercontent.com/1138060/35232314-7583f4f6-ff9b-11e7-8ee4-0a12eaae7ce2.png">

**Comment by pixiuPL** [comment]
@rodush sorry for closing it -> I just thought you solved/forgot about it. My bet.
Whats Hashicorp Atlas?

**Comment by rodush** [comment]
it is a vagrant ＋ virtualbox, so an isolated environment to test.

**Comment by pixiuPL** [comment]
@rodush Thanks a milion :) we dont use it so I dont know it.
Nonetheless, will test what you've reported.....

**Comment by mrmiagi** [comment]
We also ran into this issue while upgrading from Ubuntu 16.04.2 to 16.04.3 (official docker image):
Using phantomjs 2.1.1 we were not able to open up any https site.

What I found was that Ubuntu 16.04.3 comes with an updated `ca-certificates` package (`dpkg -l | grep ca-certificates`):

`ii  ca-certificates                       20170717~16.04.1                                         all          Common CA certificates`

Checking Ubuntu 16.04.2:

`ii  ca-certificates                       20160104ubuntu1                                      all          Common CA certificates`

No idea why but downgrading the package from `20170717~16.04.1` to `20160104ubuntu1` (`apt-get install ca-certificates=20160104ubuntu1`) resolved the issue.

I've attached the dpkg output of the downgrade:
[ca-certs-downgrade.txt](https://github.com/ariya/phantomjs/files/1659114/ca-certs-downgrade.txt)

**Comment by ariya** [comment]
Due to our very limited maintenance capacity (see #14541 for more details), we need to prioritize our development focus on other tasks. Therefore, this issue will be closed. In the future, if we see the need to attend to this issue again, then it will be reopened.
Thank you for your contribution!
